### ISSUE TITLE
Tradução - Kafka Architecture and Its Fundamental Concepts

### ISSUE THREAD

**Issue by bloiseleo** [chorumedev/KafkaDocumenter#8]
Essa [página](https://data-flair.training/blogs/kafka-architecture/) precisa de tradução.

Tópicos abordados:
- Kafka Architecture – Apache Kafka APIs
- Apache Kafka Architecture – Cluster
- Kafka Architecture – Fundamental Concepts
- Summary

**Comment by iankyy** [comment]
Tradução finalizada.
